@startuml messages-ingestion-error-handling
collections "CosmosDB" as CosmosDB
collections "Error Queue Storage" as ErrorQueueStorage
participant "ETL Function" as etlFunc
collections "Event Hub" as EventHub

activate etlFunc
CosmosDB -> etlFunc: Batch of messages metadata
' note left of etlFunc
'     A batch of is sent to the ETL function
' end note
ErrorQueueStorage -> etlFunc: Message metadata


loop Process Mesagges Metadata
  alt The function throw an error
    note left of etlFunc
     The error can be throw while processing
     while processing a batch or a single message metadata
    end note
    etlFunc -> ErrorQueueStorage: send message metadata
    note left of etlFunc
        Each item of the batch is sent individually to the queue
    end note
  else The function process the batch without throwing an error
    etlFunc -> EventHub: Send messages to the eventhub
  end
end

@enduml
