@startuml

title "Cancel massive notification job"

actor "IO COM Admin" as admin

box "pushnotif-func"
  participant "CancelMassiveJob" as httpfunc
end box

!pragma teoz true
box "io-p-itn-com-cosno-01 cosmos account" #LightBlue
  box "push-notifications cosmos database"
    database "massive-jobs" as mnj
    database "massive-progress" as mnjp
  end box
end box

box "Notification Hubs"
  participant "Notification Hub" as nh1
end box

note right of admin
  **Path Params**
    "jobId": "01KHQZBYH4GYY4Z8P5W594JG3B"
end note
admin -> httpfunc : DELETE /massive-notification-job/:jobId
activate admin
activate httpfunc

httpfunc -> httpfunc : Validate request

alt Invalid request
  httpfunc -[#red]x admin : 400
end

note right of httpfunc
  **Filters**
  {
    "jobId": "01KHQZBYH4GYY4Z8P5W594JG3B",
  }
end note
httpfunc -> mnj : Get the job
activate mnj

alt Error from comos
  mnj -[#red]> httpfunc : Transient error
  httpfunc -[#red]x admin : 500
else Job not found
  mnj -[#red]> httpfunc : 404
  httpfunc -[#red]x admin : 404
end


note right of httpfunc
  **Job Document**
  {
    "jobId": "01KHQZBYH4GYY4Z8P5W594JG3B",
    "title": "Push notification title",
    "body": "Push notification body",
    "status": "PROCESSING",
    "executionTimeInHour": 6,
    "startTime": 1771492295
  }
end note
mnj -[#green]> httpfunc : Success
deactivate mnj

note left of httpfunc
  At this point the status can be:
  - CREATED
  - PROCESSING
  - CANCELED
  - COMPLETED
end note
httpfunc -> httpfunc : Check if status is valid
alt status != PROCESSING
  note right of admin
    **Response Body**
    {
        "jobId": "01KHQZBYH4GYY4Z8P5W594JG3B",
        "error": "Jobs with status 'CREATED' cannot be canceled"
    }
    end note
    httpfunc -[#red]x admin : 406
end

note right of httpfunc
  **Filters**
  {
    "jobId": "01KHQZBYH4GYY4Z8P5W594JG3B",
    "status": "PROCESSING"
  }
end note
httpfunc -> mnjp : Get the scheduled notificaions' id
activate mnjp

alt Error from comos
  mnjp -[#red]> httpfunc : Transient error
  httpfunc -[#red]x admin : 500
end

note right of httpfunc
    **Job Progress Document list**
    [
        {
            "notificationId": "xxx",
            "jobId": "01KHQZBYH4GYY4Z8P5W594JG3B",
            "status": "PENDING"
        },
        ...
    ]
end note
mnjp -[#green]> httpfunc : 200
deactivate mnjp

loop notificationId
    httpfunc -> nh1 : Stop push notification
    activate nh1

    alt Transient/TooManyRequests from the Notification Hub
        nh1 -[#red]> httpfunc : Transient

        httpfunc -[#red]x admin : 500
    end

    alt Notification not found (404)
        nh1 -[#red]> httpfunc : 404


        httpfunc -> mnjp : Set status to "FAILED"
        activate mnjp
        alt Error from cosmos
          mnjp -[#red]> httpfunc : Transient error
          httpfunc -[#red]x admin : 500
        end
        mnjp -[#green]> httpfunc : Success
        deactivate mnjp
    else Notification Succesfully canceled
        note right of httpfunc
        **Response Body**
        {
            "notificationId": "593ca17d-7ccb-43eb-9bdd-e4b0021a24f0"
        }
        end note
        nh1 -[#green]> httpfunc : 200
        deactivate nh1

        httpfunc -> mnjp : Set status to "CANCELED"
        activate mnjp
        alt Error from cosmos
          mnjp -[#red]> httpfunc : Transient error
          httpfunc -[#red]x admin : 500
        end
    end
    mnjp -[#green]> httpfunc : Success
    deactivate mnjp
end

httpfunc -> mnj : Set status to "CANCELED"
activate mnj
alt Error from comos
  mnj -[#red]> httpfunc : Transient error
  httpfunc -[#red]x admin : 500
end

mnj -[#green]> httpfunc : Success
deactivate mnj

note right of admin
  **Response Body**
  {
    "jobId": "01KHQZBYH4GYY4Z8P5W594JG3B",
    "status": "CANCELED"
  }
end note
httpfunc -[#green]> admin : 200

deactivate httpfunc
deactivate admin
@enduml
