@startuml aar-notification-f24
participant "io-app" as ioAPP
participant "io-p-apim-v2" as ioAPIM
participant "session-manager" as sessionManager
participant "send-func" as sendFunc
participant "lollipop-func" as lollipopFunc
participant "backend-send" as beSEND

activate ioAPP
activate ioAPIM

loop richiesta F24

  note right of ioAPP
    L'applicazione ha tutti i dati della
    notifica e può richiedere
    il contenuto dell'F24.
  end note

  ioAPP -> ioAPIM: Richiesta F24
  ioAPIM -> sessionManager: Verifica sessione utente
  activate sessionManager
  break Verifica sessione utente fallita
    ioAPIM -[#red]x ioAPP: HTTP 401 - errore di autenticazione
  end
  sessionManager -> ioAPIM: Esito verifica sessione utente
  deactivate sessionManager

  note right of ioAPIM
  Sessione utente valida.
  APIM ridirige richiesta verso send-func
  end note
  ioAPIM -> sendFunc: Inoltra chiamata

  activate sendFunc
  note right of sendFunc
  Verifica la presenza e la
  correttezza degli header Lollipop
  end note
  break x-user header mancante o invalido
    sendFunc -[#red]x ioAPP: HTTP 401 -> errore di autenticazione
    else assertion ref non valido
      sendFunc -[#red]x ioAPP: HTTP 403 -> errore di autorizzazione
    else richiesta malformata
      sendFunc -[#red]x ioAPP: HTTP 400
    else errore del server
      sendFunc -[#red]x ioAPP: HTTP 500
  end


  sendFunc -> lollipopFunc: Richiesta generazione lc-params

  activate lollipopFunc
  note right of sendFunc
  Richiesta dei parametri utili a
  costruire gli headers Lollipop
  utilizzati per chiamare il backend di SEND
  end note
  break errore recupero lcparams
    sendFunc -[#red]x ioAPP: HTTP 500
  end


  lollipopFunc --> sendFunc: Restituisce lc-params
  deactivate lollipopFunc


  note right of sendFunc
  Arrichisce la richiesta con gli
  header lollipop e la inoltra al
  backend SEND
  end note
  sendFunc -> beSEND: Inoltra richiesta
  activate beSEND

  break errore del backend send
    beSEND -[#red]x sendFunc: HTTP 4xx o HTTP 5xx
    sendFunc -[#red]x ioAPP: HTTP 500
  end

  beSEND --> sendFunc: Esito richiesta
  deactivate beSEND
  alt F24 non ancora pronto
    note right of ioAPP
      Nel caso SEND risponda con un paramentro
      "retry" indicante che l'F24 non è ancora pronto,
      l'utente rimane in attesa e l'app ripete la chiamata
      per la richiesta dell'F24
    end note
    sendFunc -[#green]> ioAPP: HTTP 200
    else F24 pronto
      break
        note right of ioAPP
          L'applicazione riceve l'url dell' F24
        end note
        sendFunc -[#green]> ioAPP: HTTP 200
      end
  end
  deactivate sendFunc
end

@enduml
