@startuml aar-notification-retrieve
participant "io-app" as ioAPP
participant "io-p-apim-v2" as ioAPIM
participant "session-manager" as sessionManager
participant "send-func" as sendFunc
participant "lollipop-func" as lollipopFunc
participant "backend-send" as beSEND

activate ioAPP
activate ioAPIM


ioAPP -> ioAPP: Scansiona QRCcode su AAR SEND
ioAPP -> ioAPIM: Richiesta verifica contenuto QRCode
ioAPIM -> sessionManager: Verifica sessione utente
activate sessionManager
sessionManager -> ioAPIM: Restituisce esito verifica sessione utente
deactivate sessionManager
alt Verifica sessione utente fallita
    ioAPIM -[#red]x ioAPP: restituisce errore
end
ioAPIM -> sendFunc: Inoltra chiamata

activate sendFunc
sendFunc -> lollipopFunc: Richiesta generazione lc-params
activate lollipopFunc
lollipopFunc --> sendFunc: Esito generazione lc-params
deactivate lollipopFunc
alt Errore generazione header lollipop
    sendFunc -[#red]x ioAPP: restituisce errore
end
sendFunc -> beSEND: Inoltra richiesta aggiungendo headers lollipop

activate beSEND
beSEND --> sendFunc: Restituisce esito richiesta
deactivate beSEND
alt Error esito verifica dati QRCode
    sendFunc -[#red]x ioAPP: restituisce errore
end
sendFunc -[#green]> ioAPP: Restituisce dati per accedere alla notifica
deactivate sendFunc
deactivate ioAPIM

note right of ioAPP
    L'applicazione ha tutti i dati per recuperare
    il contentuto della notifica
end note

ioAPP -> ioAPIM: Richiede contenuto notifica
activate ioAPIM
ioAPIM -> sessionManager: Verifica sessione utente
activate sessionManager
sessionManager -> ioAPIM: Restituisce esito verifica sessione utente
deactivate sessionManager
alt Verifica sessione utente fallita
    ioAPIM -[#red]x ioAPP: restituisce errore
end
ioAPIM -> sendFunc: Inoltra chiamata

activate sendFunc
sendFunc -> lollipopFunc: Richiesta generazione lc-params
activate lollipopFunc
lollipopFunc --> sendFunc: Esito generazione lc-params
deactivate lollipopFunc
alt Errore generazione header lollipop
    sendFunc -[#red]x ioAPP: restituisce errore
end
sendFunc -> beSEND: Inoltra richiesta aggiungendo headers lollipop

activate beSEND
beSEND --> sendFunc: Restituisce esito richiesta
deactivate beSEND

alt Errore durante recupero contenuto notifica
    sendFunc -[#red]x ioAPP: restituisce errore
end
sendFunc -[#green]> ioAPP: Restituisce contenuto della notifica
deactivate sendFunc
deactivate ioAPIM
@enduml
