FROM mcr.microsoft.com/devcontainers/base:debian@sha256:6155a486f236fd5127b76af33086029d64f64cf49dd504accb6e5f949098eb7e

ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0

# Add yarn alias
RUN echo 'alias y="yarn"' >> /etc/bash.bashrc

CMD ["sleep", "infinity"]
