FROM mcr.microsoft.com/devcontainers/base:debian@sha256:da67c59f82e057e0ccb81ec7d13fb50464c26f477638018e6de1b2623a008a3a

# Add yarn alias
RUN echo 'alias y="yarn"' >> /etc/bash.bashrc

CMD ["sleep", "infinity"]
