version: "3.2"

services:
  functions-node-20:
    image: functions-node-20
    container_name: functions-node-20
    build:
      context: ./docker-files/functions-node-20
      dockerfile: ./Dockerfile
    command: /bin/true

  redis:
    container_name: redis
    image: redis:4.0.14-alpine3.11@sha256:aaf7c123077a5e45ab2328b5ef7e201b5720616efac498d55e65a7afbb96ae20
    ports:
      - 6379:6379
    environment:
      REDIS_TIMEOUT: 300
      REDIS_TCP_KEEPALIVE: 60
      REDIS_MAXMEMORY: 182m

  cosmosdb:
    image: cosmosdb
    container_name: cosmosdb
    env_file:
      - ./environments/generated/env.cosmosdb
    build:
      context: ./docker-files/cosmosdb
      dockerfile: ./Dockerfile
    ports:
      - ${COSMOSDB_PORT}:3000

  storage-account:
    image: azurite
    container_name: storage-account
    build:
      context: ./docker-files/azurite
      dockerfile: ./Dockerfile
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002

  rc-func:
    image: rc-func
    container_name: rc-func
    env_file:
      - ./environments/generated/env.rc-func
    healthcheck:
      test: ["CMD", "curl", "-f", "http://rc-func:7071/api/v1/ping"]
      interval: 12s
      timeout: 15s
      retries: 5
    build:
      context: ../apps/rc-func
      dockerfile: ../../integration-tests/docker-files/rc-func/Dockerfile
    ports:
      - ${MSGS_RC_FUNC_PORT}:7071
    links:
      - cosmosdb
      - redis
      - storage-account
    depends_on:
      - functions-node-20

  citizen-func:
    image: citizen-func
    container_name: citizen-func
    env_file:
      - ./environments/generated/env.citizen-func
    healthcheck:
      test: ["CMD", "curl", "-f", "http://citizen-func:7071/api/v1/ping"]
      interval: 12s
      timeout: 15s
      retries: 5
    build:
      context: ../apps/citizen-func
      dockerfile: ../../integration-tests/docker-files/citizen-func/Dockerfile
    ports:
      - ${MSGS_APP_FUNC_PORT}:7071
    links:
      - cosmosdb
      - redis
      - storage-account
    depends_on:
      - functions-node-20

  testagent-rc-func:
    container_name: testagent-rc-func
    image: node:20.11.1-alpine@sha256:bf77dc26e48ea95fca9d1aceb5acfa69d2e546b765ec2abfb502975f1a2d4def
    working_dir: /usr/src/app
    command: tail -f /dev/null # to keep it up&running
    env_file:
      - environments/generated/env.testagent-rc-func
    volumes:
      - "./:/usr/src/app"
      - "../apps/rc-func/openapi:/usr/src/openapi"
    depends_on:
      cosmosdb:
        condition: service_started
      storage-account:
        condition: service_started
      rc-func:
        condition: service_healthy
    links:
      - rc-func

  testagent-citizen-func:
    container_name: testagent-citizen-func
    image: node:20.11.1-alpine@sha256:bf77dc26e48ea95fca9d1aceb5acfa69d2e546b765ec2abfb502975f1a2d4def
    working_dir: /usr/src/app
    command: tail -f /dev/null # to keep it up&running
    env_file:
      - environments/generated/env.testagent-citizen-func
    volumes:
      - "./:/usr/src/app"
      - "../apps/citizen-func/openapi:/usr/src/openapi"
    depends_on:
      cosmosdb:
        condition: service_started
      storage-account:
        condition: service_started
      citizen-func:
        condition: service_healthy
    links:
      - citizen-func
