version: "3.2"

services:

  functions-node-20:
    image: functions-node-20
    build:
      context: ..
      dockerfile: ./docker/functions-node-20/Dockerfile
    command: /bin/true

  redis:
    container_name: redis
    image: wodby/redis:3.2-2.1.5
    ports:
      - "6379:6379"
    environment:
      REDIS_TIMEOUT: 300
      REDIS_TCP_KEEPALIVE: 60
      REDIS_MAXMEMORY: 182m
    networks:
      - integration-tests-net

  cosmosdb:
    image: cosmosdb
    container_name: cosmosdb
    env_file:
      - ./environments/generated/env.cosmosdb
    build:
      context: ../docker/cosmosdb
      dockerfile: ./Dockerfile
    ports:
      - ${COSMOSDB_PORT}:3000
    networks:
      - integration-tests-net

  cosmosdbrc:
    image: cosmosdb
    container_name: cosmosdbrc
    env_file:
      - ./environments/generated/env.rc.cosmosdb
    build:
      context: ../docker/cosmosdb
      dockerfile: ./Dockerfile
    ports:
      - ${RC_COSMOSDB_PORT}:3000
    networks:
      - integration-tests-net

  storage-account:
    image: azurite
    container_name: storage-account
    build:
      context: ../docker/azurite
      dockerfile: ./Dockerfile
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    networks:
      - integration-tests-net

  msgs-sending-func:
    image: msgs-sending-func
    container_name: msgs-sending-func
    env_file:
      - ./environments/generated/env.function
    healthcheck:
      test: ["CMD", "curl", "-f", "http://msgs-sending-func:7071/api/v1/ping"]
      interval: 12s
      timeout: 10s
      retries: 5
    build:
      context: ..
      dockerfile: ./docker/msgs-sending-func/Dockerfile
    ports:
      - ${FUNCTION_PORT}:7071
    links:
      - cosmosdb
      - cosmosdbrc
      - redis
      - storage-account
    depends_on:
      - functions-node-20
    networks:
      - integration-tests-net

  testagent:
    container_name: msgs-sending-func-testagent
    image: node:20.11.1-alpine
    working_dir: /usr/src/app
    command: tail -f /dev/null # to keep it up&running
    env_file:
      - environments/generated/env.integration-tests
    volumes:
      - "./:/usr/src/app"
      - "../openapi:/usr/src/openapi"
    links:
      - msgs-sending-func
    depends_on:
      cosmosdb:
        condition: service_started
      cosmosdbrc:
        condition: service_started
      storage-account:
        condition: service_started
      msgs-sending-func:
        condition: service_healthy
    networks:
      - integration-tests-net

networks:
  integration-tests-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450