version: "3.2"

services:

  functions-node-18:
    image: functions-node-18
    build:
      context: ..
      dockerfile: ./docker/functions-node-18/Dockerfile
    command: /bin/true

  redis:
    container_name: redis
    image: wodby/redis:3.2-2.1.5
    ports:
      - "6379:6379"
    environment:
      REDIS_TIMEOUT: 300
      REDIS_TCP_KEEPALIVE: 60
      REDIS_MAXMEMORY: 182m

  cosmosdb:
    image: cosmosdb
    env_file:
      - ./environments/generated/env.cosmosdb
    build:
      context: ../docker/cosmosdb
      dockerfile: ./Dockerfile
    ports:
      - ${COSMOSDB_PORT}:3000

  cosmosdbrc:
    image: cosmosdb
    container_name: cosmosdbrc
    env_file:
      - ./environments/generated/env.rc.cosmosdb
    build:
      context: ../docker/cosmosdb
      dockerfile: ./Dockerfile
    ports:
      - 3001:${RC_COSMOSDB_PORT}

  storage-account:
    image: azurite
    build:
      context: ../docker/azurite
      dockerfile: ./Dockerfile
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002

  function:
    container_name: fn-service-messages
    image: fn
    env_file:
      - ./environments/generated/env.function
    healthcheck:
      test: ["CMD", "curl", "-f", "http://function:7071/api/v1/ping"]
      interval: 12s
      timeout: 10s
      retries: 5
    build:
      context: ..
      dockerfile: ./docker/functions/Dockerfile
    ports:
      - ${FUNCTION_PORT}:7071
    links:
      - cosmosdb
      - cosmosdbrc
      - redis
      - storage-account
    depends_on:
      - functions-node-18

  testagent:
    container_name: fn-service-messages-testagent
    # FIX: use node 18 instead
    image: node:16-alpine
    working_dir: /usr/src/app
    command: tail -f /dev/null # to keep it   up&running
    env_file:
      - environments/generated/env.integration-tests
    volumes:
      - "./:/usr/src/app"
      - "../openapi:/usr/src/openapi"
    depends_on:
      cosmosdb:
        condition: service_started
      cosmosdbrc:
        condition: service_started
      storage-account:
        condition: service_started
      function:
        condition: service_healthy

    links:
      - function
