@startuml TokenizeFiscalCode

participant caller
participant TokenizeFiscalCode as tf
participant PDV
participant "ai-common" as ai

caller -> tf : call
activate tf

tf -> tf : Validate fiscal code

break Invalid input
  tf -> ai : Track the error event
  tf -> caller : Throw an error
end

tf -> PDV : Call tokenizer api

alt Error from PDV
  PDV -[#red]> tf : Error
  tf -> ai : Track the error event
  tf -> caller : Throw an error
end

PDV -[#green]> tf : token
tf -> caller : return tokenized fiscal code

@enduml
