name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - apps/**
      - packages/**

jobs:
  js_code_review:
    uses: pagopa/dx/.github/workflows/js_code_review.yaml@e392d5787298e8ef0da3fd46a07a4fed65ec4423
    name: Code Review
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
