name: Deploy (notif-func)

on:
  workflow_dispatch: {}

jobs:
  notif_func_deploy:
    uses: pagopa/dx/.github/workflows/web_app_deploy.yaml@53825edbcf12f0556a2391d716875dd928a97c69
    name: Deploy
    secrets: inherit
    with:
      workspace_name: notif-func
      environment: app-prod
      resource_group_name: io-p-itn-msgs-rg-01
      web_app_name: io-p-itn-msgs-notif-func-02
      use_staging_slot: false
      use_private_agent: true
