name: Deploy (ops-func)
permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch: {}

jobs:
  ops_func_deploy:
    uses: pagopa/dx/.github/workflows/release-azure-appsvc-v1.yaml@af75138d40e08b98e63696e26ce545004a769565
    name: Deploy
    secrets: inherit
    with:
      workspace_name: ops-func
      environment: app-prod
      resource_group_name: io-p-itn-com-rg-01
      web_app_name: io-p-itn-com-ops-func-01
      use_private_agent: true
      disable_auto_staging_deploy: true
    permissions:
      attestations: write
      contents: read
      id-token: write
