name: Deploy (cqrs-func)
permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch: {}

jobs:
  cqrs_func_deploy:
    uses: pagopa/dx/.github/workflows/release-azure-appsvc-v1.yaml@7e6e88cf29984e3a54589e1ed51a335e016b3f47
    secrets: inherit
    with:
      workspace_name: cqrs-func
      environment: app-prod
      resource_group_name: io-p-itn-com-rg-01
      web_app_name: io-p-itn-com-cqrs-func-01
      disable_auto_staging_deploy: true
    permissions:
      attestations: write
      contents: read
      id-token: write
