name: Deploy (citizen-func)

on:
  workflow_dispatch: {}

jobs:
  citizen_func_deploy:
    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@969cd49ccacd62a17aea178c7ba68ef73b0e0b34
    secrets: inherit
    with:
      workspace_name: citizen-func
      environment: app-prod
      resource_group_name: io-p-weu-com-rg-01
      function_app_name: io-p-weu-com-citizen-func-01
      health_check_path: "/api/v1/info"
      use_staging_slot: true
