name: Deploy (payment-updater)

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write
  attestations: write

jobs:
  release:
    uses: pagopa/dx/.github/workflows/release-azure-containerapp-v1.yaml@main
    name: Deploy
    secrets: inherit
    with:
      dockerfile_path: ./apps/payment-updater/Dockerfile
      dockerfile_context: ./apps/payment-updater
      docker_image_name: pagopa/io-com-payment-updater
      docker_image_description: "Payment Updater Service for IO App"
      container_app: io-p-itn-com-payment-updater-ca-01
      resource_group_name: io-p-itn-com-rg-01
      environment: app-prod
