name: Deploy (rc-app)

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write
  attestations: write

jobs:
  release:
    uses: pagopa/dx/.github/workflows/release-azure-containerapp-v1.yaml@main
    name: Deploy
    secrets: inherit
    with:
      dockerfile_path: ./apps/rc-app/Dockerfile
      dockerfile_context: .
      docker_image_name: pagopa/io-com-rc
      docker_image_description: "Microservice that handles the IO RC."
      container_app: io-p-itn-com-rc-ca-01
      resource_group_name: io-p-itn-com-rg-01
      environment: app-prod
