name: Deploy (sending-func)

on:
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy
    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@802c7c19c579c6d562496a0d6e7710978603d413
    secrets: inherit
    with:
      workspace_name: sending-func
      environment: app-prod
      resource_group_name: io-p-itn-msgs-rg-01
      function_app_name: io-p-itn-msgs-sending-func-01
      health_check_path: "/api/v1/ping"
      use_staging_slot: true
