name: Deploy (pushnotif-func)
permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch: {}

jobs:
  push_notifications_func_deploy:
    uses: pagopa/dx/.github/workflows/release-azure-appsvc-v1.yaml@036f374aa1642e539f4856696cafdf0c723ae0ab
    name: Deploy
    secrets: inherit
    with:
      workspace_name: pushnotif-func
      environment: app-prod
      resource_group_name: io-p-itn-com-rg-01
      web_app_name: io-p-itn-com-pushnotif-func-01
      use_private_agent: true
      disable_auto_staging_deploy: true
    permissions:
      attestations: write
      contents: read
      id-token: write
