name: Deploy (push-notifications-func)

on:
  workflow_dispatch: {}

jobs:
  push_notifications_func_deploy:
    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@87ca7654673290b2f80bb8d301c54dd27c4150b5
    secrets: inherit
    with:
      workspace_name: push-notifications-func
      environment: app-prod
      resource_group_name: io-p-itn-com-rg-01
      function_app_name: io-p-itn-com-pushnotif-func-01
      health_check_path: "/api/v1/info"
      use_staging_slot: true
