name: Deploy (citizen-func)

on:
  workflow_dispatch: {}

jobs:
  citizen_func_deploy:
    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@fixes/legacy-workflow-azcli
    secrets: inherit
    with:
      workspace_name: citizen-func
      environment: app-prod
      resource_group_name: io-p-itn-com-rg-01
      function_app_name: io-p-itn-com-citizen-func-01
      use_staging_slot: true
