name: Apply (resources)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/resources/**"

jobs:
  infra_release:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: Release Infrastructure
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
      use_private_agent: true
      override_github_environment: infra-prod
