name: PR Infrastructure Plan

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - ".github/workflows/infra-**.yaml"
      - "infra/resources/**"

jobs:
  infra_review:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@37c4becb6e2bee1459c53184a503868619cf1a57
    name: PR Prod WestEurope
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
      use_private_agent: true
