name: Labeler

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    name: PR Labeler
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Label PR
        uses: actions/labeler@6463cdb00ee92c05bec55dffc4e1fce250301945
        with:
          sync-labels: true
