name: Deploy Function App (sending-func)

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - "apps/sending-func/CHANGELOG.md"
      - ".github/workflows/msgs-sending-func-deploy.yaml"

jobs:
  deploy:
    name: Deploy
    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@main
    secrets: inherit
    with:
      workspace_name: sending-func
      environment: app-prod
      resource_group_name: io-p-itn-msgs-rg-01
      function_app_name: io-p-itn-msgs-sending-func-01
      health_check_path: "/api/v1/ping"
      use_staging_slot: true
