name: Deploy (notif-func)

on:
  workflow_dispatch:

jobs:
  notif_func_deploy:
    uses: pagopa/dx/.github/workflows/web_app_deploy.yaml@add-web-app-deploy-workflow
    name: Deploy
    secrets: inherit
    with:
      workspace_name: notif-func
      environment: app-prod
      resource_group_name: io-p-itn-msgs-rg-01
      web_app_name: io-p-itn-msgs-notif-func-01
      health_check_path: /api/health
      use_staging_slot: false
      use_private_agent: true
