name: Plan (github-runner)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "infra/github-runner/**"
      - ".github/workflows/pr_github_runner.yaml"

jobs:
  runner_review:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: PR Prod WestEurope
    secrets: inherit
    with:
      environment: "prod"
      base_path: "infra/github-runner"
