name: Static Analysis

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "infra/resources/**"

jobs:
  static_analysis:
    uses: pagopa/dx/.github/workflows/static_analysis.yaml@main
    name: Terraform Validation
    secrets: inherit
